//
//  TestSuccessGithubRepository.swift
//  iOSEngineerCodeCheckTests
//
//  Created by kento.yamazaki on 2025/02/26.
//  Copyright © 2025 YUMEMI Inc. All rights reserved.
//

import Foundation
import UIKit
@testable
import iOSEngineerCodeCheck

// MARK: - TestSuccessGithubRepository

final class TestSuccessGithubRepository: GithubRepositoryProtocol {
    required init(session _: URLSession) {
        // セッションは使用しない
    }

    func searchRepositories(query _: String, sort _: String, order _: String, page _: Int, perPage _: Int) async throws -> GithubRepositoryResponseEntity {
        return .init(
            totalCount: 2,
            incompleteResults: false,
            items: [
                // 正常なデータ
                GithubRepositoryEntity(
                    id: 1,
                    nodeId: "node123",
                    name: "ExampleRepo",
                    fullName: "Swift/Example",
                    owner: GithubOwnerEntity(
                        login: "user1",
                        id: 101,
                        nodeId: "ownerNode123",
                        avatarURL: "https://example.com/avatar.png",
                        gravatarId: nil,
                        url: "https://api.github.com/users/user1",
                        receivedEventsURL: "https://api.github.com/users/user1/received_events",
                        type: "User",
                        htmlURL: "https://github.com/user1",
                        followersURL: "https://api.github.com/users/user1/followers",
                        followingURL: "https://api.github.com/users/user1/following{/other_user}",
                        gistsURL: "https://api.github.com/users/user1/gists{/gist_id}",
                        starredURL: "https://api.github.com/users/user1/starred{/owner}{/repo}",
                        subscriptionsURL: "https://api.github.com/users/user1/subscriptions",
                        organizationsURL: "https://api.github.com/users/user1/orgs",
                        reposURL: "https://api.github.com/users/user1/repos",
                        eventsURL: "https://api.github.com/users/user1/events{/privacy}",
                        siteAdmin: false
                    ),
                    isPrivate: false,
                    htmlURL: "https://github.com/Swift/Example",
                    description: "An example repository",
                    isFork: false,
                    url: "https://api.github.com/repos/Swift/Example",
                    createdAt: "2023-01-01T00:00:00Z",
                    updatedAt: "2023-01-02T00:00:00Z",
                    pushedAt: "2023-01-03T00:00:00Z",
                    homepage: "https://example.com",
                    size: 1024,
                    stargazersCount: 100,
                    watchersCount: 50,
                    language: "Swift",
                    forksCount: 30,
                    openIssuesCount: 10,
                    masterBranch: "main",
                    defaultBranch: "main",
                    score: 1,
                    archiveURL: "https://api.github.com/repos/Swift/Example/{archive_format}{/ref}",
                    assigneesURL: "https://api.github.com/repos/Swift/Example/assignees{/user}",
                    blobsURL: "https://api.github.com/repos/Swift/Example/git/blobs{/sha}",
                    branchesURL: "https://api.github.com/repos/Swift/Example/branches{/branch}",
                    collaboratorsURL: "https://api.github.com/repos/Swift/Example/collaborators{/collaborator}",
                    commentsURL: "https://api.github.com/repos/Swift/Example/comments{/number}",
                    commitsURL: "https://api.github.com/repos/Swift/Example/commits{/sha}",
                    compareURL: "https://api.github.com/repos/Swift/Example/compare/{base}...{head}",
                    contentsURL: "https://api.github.com/repos/Swift/Example/contents/{+path}",
                    contributorsURL: "https://api.github.com/repos/Swift/Example/contributors",
                    deploymentsURL: "https://api.github.com/repos/Swift/Example/deployments",
                    downloadsURL: "https://api.github.com/repos/Swift/Example/downloads",
                    eventsURL: "https://api.github.com/repos/Swift/Example/events",
                    forksURL: "https://api.github.com/repos/Swift/Example/forks",
                    gitCommitsURL: "https://api.github.com/repos/Swift/Example/git/commits{/sha}",
                    gitRefsURL: "https://api.github.com/repos/Swift/Example/git/refs{/sha}",
                    gitTagsURL: "https://api.github.com/repos/Swift/Example/git/tags{/sha}",
                    gitURL: "git://github.com/Swift/Example.git",
                    issueCommentURL: "https://api.github.com/repos/Swift/Example/issues/comments{/number}",
                    issueEventsURL: "https://api.github.com/repos/Swift/Example/issues/events{/number}",
                    issuesURL: "https://api.github.com/repos/Swift/Example/issues{/number}",
                    keysURL: "https://api.github.com/repos/Swift/Example/keys{/key_id}",
                    labelsURL: "https://api.github.com/repos/Swift/Example/labels{/name}",
                    languagesURL: "https://api.github.com/repos/Swift/Example/languages",
                    mergesURL: "https://api.github.com/repos/Swift/Example/merges",
                    milestonesURL: "https://api.github.com/repos/Swift/Example/milestones{/number}",
                    notificationsURL: "https://api.github.com/repos/Swift/Example/notifications{?since,all,participating}",
                    pullsURL: "https://api.github.com/repos/Swift/Example/pulls{/number}",
                    releasesURL: "https://api.github.com/repos/Swift/Example/releases{/id}",
                    sshURL: "git@github.com:Swift/Example.git",
                    stargazersURL: "https://api.github.com/repos/Swift/Example/stargazers",
                    statusesURL: "https://api.github.com/repos/Swift/Example/statuses/{sha}",
                    subscribersURL: "https://api.github.com/repos/Swift/Example/subscribers",
                    subscriptionURL: "https://api.github.com/repos/Swift/Example/subscription",
                    tagsURL: "https://api.github.com/repos/Swift/Example/tags",
                    teamsURL: "https://api.github.com/repos/Swift/Example/teams",
                    treesURL: "https://api.github.com/repos/Swift/Example/git/trees{/sha}",
                    cloneURL: "https://github.com/Swift/Example.git",
                    mirrorURL: nil,
                    hooksURL: "https://api.github.com/repos/Swift/Example/hooks",
                    svnURL: "https://svn.github.com/Swift/Example",
                    forks: 30,
                    openIssues: 10,
                    watchers: 50,
                    hasIssues: true,
                    hasProjects: true,
                    hasPages: true,
                    hasWiki: true,
                    hasDownloads: true,
                    archived: false,
                    disabled: false,
                    visibility: "public",
                    license: GithubLicenseEntity(
                        key: "mit",
                        name: "MIT License",
                        url: "https://api.github.com/licenses/mit",
                        spdxId: "MIT",
                        nodeId: "MDc6TGljZW5zZW1pdA==",
                        htmlURL: "https://api.github.com/licenses/mit"
                    )
                ),
                // 不完全なデータ
                GithubRepositoryEntity(
                    id: 2,
                    nodeId: "",
                    name: "",
                    fullName: "",
                    owner: GithubOwnerEntity(
                        login: "",
                        id: 0,
                        nodeId: "",
                        avatarURL: "",
                        gravatarId: nil,
                        url: "",
                        receivedEventsURL: "",
                        type: "",
                        htmlURL: "",
                        followersURL: "",
                        followingURL: "",
                        gistsURL: "",
                        starredURL: "",
                        subscriptionsURL: "",
                        organizationsURL: "",
                        reposURL: "",
                        eventsURL: "",
                        siteAdmin: false
                    ),
                    isPrivate: false,
                    htmlURL: "",
                    description: nil,
                    isFork: false,
                    url: "",
                    createdAt: "",
                    updatedAt: "",
                    pushedAt: "",
                    homepage: nil,
                    size: 0,
                    stargazersCount: 0,
                    watchersCount: 0,
                    language: nil,
                    forksCount: 0,
                    openIssuesCount: 0,
                    masterBranch: nil,
                    defaultBranch: "",
                    score: 0,
                    archiveURL: "",
                    assigneesURL: "",
                    blobsURL: "",
                    branchesURL: "",
                    collaboratorsURL: "",
                    commentsURL: "",
                    commitsURL: "",
                    compareURL: "",
                    contentsURL: "",
                    contributorsURL: "",
                    deploymentsURL: "",
                    downloadsURL: "",
                    eventsURL: "",
                    forksURL: "",
                    gitCommitsURL: "",
                    gitRefsURL: "",
                    gitTagsURL: "",
                    gitURL: "",
                    issueCommentURL: "",
                    issueEventsURL: "",
                    issuesURL: "",
                    keysURL: "",
                    labelsURL: "",
                    languagesURL: "",
                    mergesURL: "",
                    milestonesURL: "",
                    notificationsURL: "",
                    pullsURL: "",
                    releasesURL: "",
                    sshURL: "",
                    stargazersURL: "",
                    statusesURL: "",
                    subscribersURL: "",
                    subscriptionURL: "",
                    tagsURL: "",
                    teamsURL: "",
                    treesURL: "",
                    cloneURL: "",
                    mirrorURL: nil,
                    hooksURL: "",
                    svnURL: "",
                    forks: 0,
                    openIssues: 0,
                    watchers: 0,
                    hasIssues: false,
                    hasProjects: false,
                    hasPages: false,
                    hasWiki: false,
                    hasDownloads: false,
                    archived: false,
                    disabled: false,
                    visibility: "",
                    license: nil
                ),
            ]
        )
    }
}
